services:
  server:
    image: blog-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/postgres
      SECRET: thisisaverylongandsecuresecret
    depends_on:
      db:
        condition: service_healthy
        restart: true
    container_name: blog-server

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
    container_name: blog-db

volumes:
  postgres_data:
