POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGUzQGdtYWlsLmNvbSIsImlkIjo0LCJpYXQiOjE3NzE2OTc3MzJ9.ovzJ2CIi3UvTrbJucDjW1GHCMcDJenEb-C6MMHWZ2PU
                      
{
  "title": "Blogging again disabled",
  "author": "Best Author",
  "url": "https://example.com",
  "year": 2026,
  "likes": 30
}